export const PERSONAL_QUESTIONS = [
  { id: 'profile', title: 'What does a race near my target look like?', focuses: ['prepare', 'review'], method: 'Select finishes in the displayed 15-minute finish-time band, centered on the nearest 15-minute target preset. Show each section’s median pace and middle 50% of observed paces. These are achieved times, not declared goals, and the profile is not an optimal pacing plan.' },
  { id: 'opening', title: 'Which openings are associated with finishing under my target?', focuses: ['prepare'], method: 'Use runners with a recorded best in the two strictly earlier calendar years. Classify the first 10 km as more than 2% faster than that benchmark’s marathon pace, within 2%, or more than 2% slower. For each group, count finishes strictly below the selected time. Groups are observational and pool available editions; a prior-time filter narrows ability but does not eliminate confounding.' },
  { id: 'sections', title: 'Where do nearby finishes gain or lose time?', focuses: ['prepare', 'review'], method: 'Compare finishes in the five minutes strictly below the selected target with finishes from the target up to, but excluding, five minutes above it. Subtract the target’s even-pace time budget from each mean section duration. Means reconcile with mean finish-time differences; selection on the outcome makes this descriptive.' },
  { id: 'age', title: 'How does pacing differ across age groups?', focuses: ['prepare', 'review'], method: 'Compare median percentage pace change from 0–20 to 20–40 km across exact-age bands. When previous performance is supplied, compare the same 15-minute prior-time band. Otherwise compare the same displayed achieved-time band. Gender and course are held to the displayed selection. This is a comparison of different people, not an individual aging trajectory.' },
  { id: 'terrain', title: 'What pace changes appear alongside the supplied terrain?', focuses: ['prepare', 'review'], method: 'Align the supplied unique city-level course segments with the pacing profile. Historical route validity is unknown. Net elevation change can hide both climbing and descending; bridge decks, tunnels, smoothing and route changes can affect the profile. This does not estimate a historical hill penalty or grade-adjusted effort.' },
  { id: 'downhill', title: 'What follows a fast opening on a downhill-start profile?', focuses: ['prepare'], method: 'Identify a net-downhill opening from the first two supplied 5 km terrain segments. Among the earlier-benchmark opening groups, compare median pace change from the 5–20 km baseline to the final 12.195 km. The supplied route is a proxy, and these associations do not establish that an early descent caused later slowing. Where no downhill opening is documented, show the general opening comparison and say so.' },
  { id: 'checkpoint', title: 'What happened to runners at a similar checkpoint time?', focuses: ['prepare', 'review'], method: 'Match course, available age/gender groups, checkpoint and a two-minute elapsed-time band at 20, 30 or 35 km. Optional recent-5-km pace is classified relative to elapsed average pace using ±2%. The previous-marathon filter is not used because this comparison conditions on current-race progress. Show historical finish percentiles and the fraction below the visitor’s threshold, not a calibrated personal probability. Only complete eligible finishers are represented.' },
  { id: 'courses', title: 'How do outcomes and consistency vary across courses?', focuses: ['choose'], method: 'For the same displayed age, gender and prior-time cohort across courses, show the 10th, 50th and 90th percentiles of finish-time change relative to the recent recorded best. Require at least 100 observations and three editions per course. Use identical cohort criteria across the displayed courses. These different runners and editions do not isolate a course effect or provide equivalent-time predictions.' },
  { id: 'weather', title: 'How do outcomes differ across cooler and warmer editions?', focuses: ['prepare', 'choose'], method: 'Use the supplied modeled start-hour temperature and runners with earlier benchmarks. Compute edition-level median finish-time change, requiring 20 finishes per edition/group. Average edition medians equally within temperature bands, requiring three editions and 100 finishes. Weather exposure is a start-hour proxy, not personal exposure; humidity, sun, wind and route changes are not isolated.' },
  { id: 'ambition', title: 'Where does my target sit among comparable results?', focuses: ['prepare', 'choose'], method: 'Evaluate the selected time against the historical finish-time distribution in the displayed cohort. Optional previous performance selects a 15-minute band of recent recorded bests. Each whole-minute threshold from 1:30 through 12:00 is calculated exactly using a strict less-than comparison. Without previous performance this describes the selected field, not individual readiness.' },
  { id: 'return', title: 'How do runners change when they return to this course?', focuses: ['prepare', 'review'], method: 'Use consecutive linked appearances in different years, at most three years apart, on the same city course, requiring one eligible recorded race in both endpoint years. Apply the profile to the later appearance and compare both observed section profiles, each normalized to its own finish. Report paired mean finish-time change. Route changes, fitness and selection remain possible explanations; first recorded is not first ever.' },
  { id: 'gains', title: 'Where did runners improving toward this time gain minutes?', focuses: ['prepare', 'review'], method: 'Select finishes in the displayed achieved-time band that beat the runner’s fastest recorded finish from strictly earlier years. Compare durations in the opening 10 km, middle 20 km and final 12.195 km with that earlier result. Mean block gains sum to mean finish improvement. This is an earlier recorded best, not a lifetime personal best or a prescription for a future improvement.' },
] as const;

export const GOAL_MIN = 90;
export const GOAL_MAX = 720;
export const GOAL_PRESETS = Array.from({ length: (GOAL_MAX - GOAL_MIN) / 15 + 1 }, (_, i) => GOAL_MIN + i * 15);
export const AGE_OPTIONS = ['all', '18–24', ...Array.from({ length: 13 }, (_, i) => `${25 + i * 5}–${29 + i * 5}`)];
export type Focus = 'prepare' | 'choose' | 'review';
export type Profile = { city: string; age: string; gender: string; goal: number; previous: number | null; focus: Focus };
