export type AnalysisId = 'profile' | 'opening' | 'checkpoint' | 'sections' | 'courses' | 'weather' | 'terrain' | 'ambition' | 'gains' | 'age';
export type AnalysisDefinition = {
  id: AnalysisId; slug: string; rank: number; title: string; shortTitle: string;
  description: string; purpose: string; readChart: string; caution: string;
  category: 'Plan your race' | 'Know your course' | 'Understand your result';
  controls: { course: boolean; time: boolean; age: boolean; gender: boolean; previous: boolean };
};

const all = { course: true, time: true, age: true, gender: true, previous: true };
export const TEN_ANALYSES: AnalysisDefinition[] = [
  { id: 'profile', slug: 'pacing-pattern', rank: 1, title: 'How do runners near my time pace the race?', shortTitle: 'Your pacing pattern', category: 'Plan your race', description: 'See the rhythm of a marathon, from the first 5 km to the finish.', purpose: 'Start here. A finish time tells you how long a race took. The splits show how it unfolded.', readChart: 'The line shows the typical pace for each section. Higher means slower. The shaded area contains the middle half of the observed paces.', caution: 'These runners achieved similar finish times. Their pattern is a comparison, not a recommended pacing plan.', controls: all },
  { id: 'opening', slug: 'starting-pace', rank: 2, title: 'What happens after a very fast start?', shortTitle: 'Fast starts, late slowing', category: 'Plan your race', description: 'Follow a fast start through late slowing, its onset and the finish time.', purpose: 'Compare quick openings within each race, then see where sustained slowing began and how the minutes accumulated. Earlier-result comparisons are also available.', readChart: 'Compare six opening groups using each race’s early pace or an earlier recorded best. Trace section pace, later time differences and the first sustained-slowdown section.', caution: 'A quick first section does not establish that the entire opening was too ambitious. These recorded differences cannot isolate a penalty caused by starting fast.', controls: { ...all, time: false } },
  { id: 'checkpoint', slug: 'checkpoint', rank: 3, title: 'What can my checkpoint time tell me?', shortTitle: 'From here to the finish', category: 'Plan your race', description: 'Enter a time at 20, 30 or 35 km and explore the finishes that followed.', purpose: 'Put a moment in the race into context. Compare your elapsed time with runners who reached the same checkpoint at a similar time.', readChart: 'The finish-time range describes historical runners at similar progress. The required pace is calculated directly from your entered time and target.', caution: 'Only runners with complete finishes are represented. This is historical context, not your personal probability of finishing.', controls: { ...all, previous: false } },
  { id: 'sections', slug: 'where-time-is-gained', rank: 4, title: 'Where is a target time won or lost?', shortTitle: 'The minutes that matter', category: 'Understand your result', description: 'Look section by section at runners just under and just over a target.', purpose: 'Two close finish times can hide very different races. Find the sections where those paths separate.', readChart: 'Zero is the even-pace budget for your selected time. A positive bar means more minutes spent in that section; a negative bar means fewer.', caution: 'The groups are chosen by their eventual finish. Differences show what happened, not what caused the result.', controls: all },
  { id: 'courses', slug: 'course-comparison', rank: 5, title: 'How does pacing compare across courses?', shortTitle: 'Compare the courses', category: 'Know your course', description: 'Compare late slowing and pacing across courses, with an earlier-result option.', purpose: 'See how race fields hold their pace across courses. No earlier result is needed for the default view.', readChart: 'The default gives each qualifying edition equal weight. In the earlier-result view, the dot is the typical change from an earlier best and the line spans the middle 80% of observed results.', caution: 'Different fields, fitness changes and race days remain mixed together. This is not a ranking of course difficulty.', controls: { ...all, course: false, time: false } },
  { id: 'weather', slug: 'race-day-weather', rank: 6, title: 'How do warm and cool races compare?', shortTitle: 'Race-day weather', category: 'Know your course', description: 'Explore observed results across start-hour temperature bands.', purpose: 'Conditions are part of the race. Compare cooler and warmer editions while keeping each race day equally weighted.', readChart: 'Compare edition-average slowing across temperature bands. Each qualifying edition contributes equally. A separate earlier-result view compares finishes with recorded bests.', caution: 'Start-hour temperature is an estimate. Wind, humidity, sunshine, fitness and course differences are not isolated.', controls: { ...all, time: false } },
  { id: 'terrain', slug: 'hills-and-pacing', rank: 7, title: 'Where do hills and pace changes line up?', shortTitle: 'Hills and rhythm', category: 'Know your course', description: 'Place the supplied elevation profile beside observed section paces.', purpose: 'Choose a course to see its larger rises and falls, then compare the pacing pattern at the same distances.', readChart: 'Positive elevation change means the section ends higher than it starts. Switch to the pacing view to compare the same sections.', caution: 'The supplied route may differ from older editions. Net elevation hides climbs followed by descents; it cannot give a precise hill penalty.', controls: all },
  { id: 'ambition', slug: 'finish-time-context', rank: 8, title: 'How does my target compare with the field?', shortTitle: 'Your target in context', category: 'Plan your race', description: 'See where a selected finish time falls among comparable results.', purpose: 'A target means something different in every field. Put a time in context, with an earlier result if you have one.', readChart: 'The percentage counts finishes strictly below your selected time. The median is the point with half the results on either side.', caution: 'A place in the historical field does not measure your readiness. Training, health and race-day conditions are not recorded here.', controls: all },
  { id: 'gains', slug: 'finding-improvement', rank: 9, title: 'Where do improving runners find time?', shortTitle: 'Where improvement happens', category: 'Understand your result', description: 'Find the opening, middle and late-race minutes behind improved finishes.', purpose: 'Improvement is more revealing when you can see where it appeared. Compare faster races with the same runners’ earlier bests.', readChart: 'Positive values are minutes gained in each part of the race. The three parts add up to the average improvement.', caution: 'An earlier recorded best may not be a lifetime personal best. The comparison includes runners whose histories could be linked.', controls: all },
  { id: 'age', slug: 'age-and-pacing', rank: 10, title: 'How does pacing differ across age groups?', shortTitle: 'Age and pace retention', category: 'Understand your result', description: 'Compare the ability to hold pace across ages and recorded genders.', purpose: 'Age and finishing speed are different questions. Compare age groups within a similar time band.', readChart: 'The bars compare the second 20 km with the first 20 km. Higher means more slowing. The final 2.195 km is excluded from this equal-distance comparison.', caution: 'These are different people, not the same runners followed as they age. Many records have no exact age and cannot enter these groups.', controls: { ...all, age: false } },
];

export const analysisHref = (item: AnalysisDefinition) => '/analyses/' + item.slug;
export function analysisBySlug(slug: string) { return TEN_ANALYSES.find(item => item.slug === slug); }
